title: Journey towards learning
author: Sandeep More
email: sandeep.moore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Create, Learn and Share

# social links
twitter_username: sandyonmars # DO NOT include the @ character, or else the build will fail!
github_username:  sandyonmars # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
